apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: nextcloud
type: Opaque
data:
  MYSQL_USER: ase64_encoded_user
  MYSQL_ROOT_PASSWORD: ase64_encoded_password
  MYSQL_DATABASE: ase64_encoded_database_name
  MYSQL_PASSWORD: base64_encoded_password
