###Create a the same pv-pvc file for each deployment###

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-database
spec:
  capacity:
    storage: 2Gi
  storageClassName: fast
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs_server_ip
    path: /persistant/path/nginx

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fast    
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-database
